game: War Thunder
api: 1
steamID: 236390
uid: com.thegreatcabbage.warthunder
author: TheGreatCabbage
packageName: warthunder

graphicsConfig: config.blk
keymapConfig: "D:/Documents/My Games/WarThunder/Saves/11096205/production"

gameDirectory: War Thunder
verificationPaths:
  - launcher.exe
  - win64